# Generated by Django 5.2.1 on 2025-05-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_article_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Аты')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('subject', models.CharField(max_length=200, verbose_name='Тақырып')),
                ('message', models.TextField(verbose_name='Хабарлама')),
            ],
            options={
                'verbose_name': 'Байланыс хаты',
                'verbose_name_plural': 'Байланыс хаттары',
            },
        ),
    ]
