# Generated by Django 5.2.1 on 2025-05-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contact_message'),
        ),
    ]
