# Generated by Django 5.2.1 on 2025-05-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_article_content_en_article_content_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram ID'),
        ),
    ]
